### ISSUE TITLE
System.Data.Entity.Core.EntityCommandCompilationException with Npgsql

### ISSUE THREAD

**Issue by FruitAndAShape** [glueckkanja/codefirstfunctions#1]
In my context, I have...

`modelBuilder.Conventions.Add(new FunctionsConvention<DomainDbContext>("public"));`

...and

        [DbFunction("CodeFirstDatabaseSchema", "geodistance")]
        public static double geodistance(double fromLat, double fromLong,
            double toLat, double toLong)
        {
            throw new NotSupportedException();
        }

In the select of the query, I have...

`Distance = DomainDbContext.geodistance(45, 45, 45, 45)`

When I run the query I get a EntityCommandCompilationException with the following message...

> Specified method is not supported.

Any ideas?

**Comment by Jabe** [comment]
Hi, we originally forked the upstream project (https://codefirstfunctions.codeplex.com/) to make some minor changes, but with EF 7 coming this has become obsolete. Try opening an issue here: https://codefirstfunctions.codeplex.com/workitem/list/basic
